### ISSUE TITLE
Error when get profile after success auth

### ISSUE THREAD

**Issue by maxvanceffer** [manjeshpv/node-oauth2-server-implementation#28]
```
SequelizeEagerLoadingError: User is not associated to OAuthAccessToken!
    at Function._getIncludedAssociation (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:583:13)
    at Function._validateIncludedElement (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:1576:14)
    at tryCatcher (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
SequelizeEagerLoadingError: User is not associated to OAuthAccessToken!
    at Function._getIncludedAssociation (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:583:13)
    at Function._validateIncludedElement (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:499:53)
    at options.include.options.include.map.include (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/home/dev06/projects/bb/server/node_modules/sequelize/lib/model.js:1576:14)
    at tryCatcher (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/dev06/projects/bb/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**Comment by zzy503886330** [comment]
@maxvanceffer  Have you solved it?
